apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fococero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 486507079259.dkr.ecr.us-east-1.amazonaws.com/fococero-api-gateway:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            # URLs de Microservicios (DNS interno de K8s)
            - name: AUTH_SERVICE_URL
              value: "http://ms-auth:3001"
            - name: REPORTES_SERVICE_URL
              value: "http://ms-reportes:3004"
            - name: ALERTAS_SERVICE_URL
              value: "http://ms-alertas:3003"
            # Seguridad
            - name: INTERNAL_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: INTERNAL_SECRET_TOKEN
            # Firebase
            - name: FIREBASE_PROJECT_ID
              value: "${FIREBASE_PROJECT_ID}"
            - name: FIREBASE_CLIENT_EMAIL
              value: "${FIREBASE_CLIENT_EMAIL}"
            # Eureka Desactivado
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "false"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
