apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fococero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 663719127850.dkr.ecr.us-east-1.amazonaws.com/fococero-api-gateway:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"
            # URLs de Microservicios
            - name: AUTH_SERVICE_URL
              value: "http://ms-auth:3001"
            - name: REPORTES_SERVICE_URL
              value: "http://ms-reportes:3004"
            - name: ALERTAS_SERVICE_URL
              value: "http://ms-alertas:3003"
            - name: GEO_SERVICE_URL
              value: "http://ms-geo:3002"
            - name: MULTIMEDIA_SERVICE_URL
              value: "http://ms-multimedia:3005"
            - name: EMERGENCIAS_SERVICE_URL
              value: "http://ms-emergencias:3006"
            - name: ANALITICA_SERVICE_URL
              value: "http://ms-analitica:3007"
            # CORS: Orígenes permitidos (separados por coma)
            - name: CORS_ORIGINS
              value: "http://localhost:5173,http://localhost:3000,http://ad57769170d9f4acdab82d17cd091c92-7f35ff8f99b3f857.elb.us-east-1.amazonaws.com"
            # Seguridad: Inyectado desde el secreto api-gateway-secrets
            - name: INTERNAL_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-gateway-secrets
                  key: INTERNAL_SECRET_TOKEN
            # Firebase: Inyectado desde el pipeline (cd.yml)
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                {
                  secretKeyRef:
                    { name: firebase-secret, key: FIREBASE_PROJECT_ID },
                }
            - name: FIREBASE_CLIENT_EMAIL
              valueFrom:
                {
                  secretKeyRef:
                    { name: firebase-secret, key: FIREBASE_CLIENT_EMAIL },
                }
            - name: FIREBASE_PRIVATE_KEY
              valueFrom:
                {
                  secretKeyRef:
                    { name: firebase-secret, key: FIREBASE_PRIVATE_KEY },
                }
            # Eureka Desactivado
            - name: EUREKA_CLIENT_REGISTERWITHEUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCHREGISTRY
              value: "false"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
