apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: fococero
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 711147367899.dkr.ecr.us-east-1.amazonaws.com/fococero-apigetway:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: AUTH_SERVICE_URL
              value: "http://ms-auth:3001"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
