name: CD - Desplegar api-gateway en EKS
on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY}}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME}}

jobs:
  desplegar:
    name: Desplegar en EKS
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Iniciar sesion en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y publicar imagen Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Actualizar kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Aplicar namespace
        run: |
          kubectl create namespace fococero --dry-run=client -o yaml | kubectl apply -f -

      - name: Crear secreto de api-gateway
        run: |
          kubectl create secret generic api-gateway-secrets \
            --from-literal=INTERNAL_SECRET_TOKEN="${{ secrets.INTERNAL_SECRET_TOKEN }}" \
            -n fococero \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Crear secreto de Firebase
        run: |
          printf '%s\n' "${{ secrets.FIREBASE_PRIVATE_KEY }}" | sed -e 's/\\n/\n/g' > /tmp/firebase-key.pem
          
          kubectl create secret generic firebase-secret \
            --from-literal=FIREBASE_PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}" \
            --from-literal=FIREBASE_CLIENT_EMAIL="${{ secrets.FIREBASE_CLIENT_EMAIL }}" \
            --from-file=FIREBASE_PRIVATE_KEY=/tmp/firebase-key.pem \
            -n fococero \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Desplegar en EKS
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" k8s/api-gateway-deployment.yaml
          kubectl apply -f k8s/api-gateway-deployment.yaml
          kubectl apply -f k8s/api-gateway-service.yaml
          kubectl apply -f k8s/api-gateway-hpa.yaml
